model_name: tr_detr
dset_name: charades
ctx_mode: video_tef
v_feat_types: clip
t_feat_type: clip
train_path: data/charades/charades_train_release.jsonl
eval_path: data/charades/charades_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/Charades/clip']
t_feat_dir: features/Charades/clip_text
v_feat_dim: 514
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_tr_detr/charades
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log

# charades-specific params
lw_saliency: 4
lr: 0.0002
lr_drop: 40

# TR-DETR specific losses
VTC_loss_coef: 0.3
CTC_loss_coef: 0.5