model_name: taskweave
dset_name: charades
ctx_mode: video_tef
v_feat_types: slowfast_clip
t_feat_type: clip
train_path: data/charades/charades_train_release.jsonl
eval_path: data/charades/charades_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/Charades/clip', 'features/Charades/slowfast']
t_feat_dir: features/Charades/clip_text
v_feat_dim: 2818
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast_taskweave_mr2hd/charades
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log

# Taskweave-specific; This model needs to train MR2HD and HD2MR for MR and HD, respectively.
# If mr2hd is False, the strategy is HD2MR
mr2hd: True
model_ema: True

# charades-specific params
lw_saliency: 4
lr: 0.0002
lr_drop: 40