model_name: cg_detr
dset_name: qvhighlight
ctx_mode: video_audio_tef
v_feat_types: slowfast_clip
a_feat_types: pann
t_feat_type: clip
train_path: data/qvhighlight/highlight_train_release.jsonl
eval_path: data/qvhighlight/highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/QVHighlight/clip', 'features/QVHighlight/slowfast']
a_feat_dirs: ['features/QVHighlight/pann']
t_feat_dir: features/QVHighlight/clip_text
v_feat_dim: 2818
a_feat_dim: 2048
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast_pann_cg_detr/qvhighlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# CG-DETR-specific parameters
enc_layers: 3
dec_layers: 3
t2v_layers: 2
sent_layers: 1
moment_layers: 1
dummy_layers: 2
num_dummies: 45
total_prompts: 10
num_prompts: 2

lw_saliency: 1
lw_wattn: 1
lw_ms_align: 1
lw_distill: 1