model_name: qd_detr
dset_name: qvhighlight
ctx_mode: video_audio_tef
v_feat_types: clip
a_feat_types: pann
t_feat_type: clip
train_path: data/qvhighlight/highlight_train_release.jsonl
eval_path: data/qvhighlight/highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/QVHighlight/clip']
a_feat_dirs: ['features/QVHighlight/pann']
t_feat_dir: 'features/QVHighlight/clip_text'
v_feat_dim: 514
a_feat_dim: 2048
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_pann/qd_detr/qvhighlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2