model_name: taskweave
dset_name: qvhighlight
ctx_mode: video_tef
v_feat_types: clip
t_feat_type: clip
train_path: data/qvhighlight/highlight_train_release.jsonl
eval_path: data/qvhighlight/highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/QVHighlight/clip']
t_feat_dir: features/QVHighlight/clip_text
v_feat_dim: 514
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_taskweave_mr2hd/qvhighlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# Taskweave-specific; This model needs to train MR2HD and HD2MR for MR and HD, respectively.
# If mr2hd is False, the strategy is HD2MR
mr2hd: True
model_ema: True