model_name: qd_detr
dset_name: qvhighlight
ctx_mode: video_tef
v_feat_types: resnet
t_feat_type: glove
train_path: data/qvhighlight/highlight_train_release.jsonl
eval_path: data/qvhighlight/highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/QVHighlight/resnet']
t_feat_dir: features/QVHighlight/glove
v_feat_dim: 2050
t_feat_dim: 300
aux_loss: True
results_dir: results/resnet_glove_qd_detr/qvhighlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2