model_name: qd_detr
dset_name: qvhighlight
ctx_mode: video_audio_tef
v_feat_types: slowfast_clip
#a_feat_types: clap
a_feat_types: panns
t_feat_type: clip
train_path: data/qvhighlight/highlight_train_release.jsonl
eval_path: data/qvhighlight/highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/QVHighlight/clip', 'features/QVHighlight/slowfast']
#a_feat_dirs: ['features/QVHighlight/clap/sec=2s_hop_sec=2s'] # clap
a_feat_dirs: ['/root/workspace/sharing/mm-va-cg-share/share/dataset/video_moment_retrieval/QVHighlight/pann'] # panns
t_feat_dir: 'features/QVHighlight/clip_text'
t_feat_aud_dir: 'features/QVHighlight/clap_text'
v_feat_dim: 2818
#a_feat_dim: 1024 # clap
a_feat_dim: 2048 # panns
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast/panns/qd_detr/qvhighlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2