model_name: qd_detr
dset_name: tacos
ctx_mode: video_tef
v_feat_types: slowfast_clip
t_feat_type: clip
train_path: data/tacos/tacos_train_release.jsonl
eval_path: data/tacos/tacos_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tacos/clip', 'features/tacos/slowfast']
t_feat_dir: features/tacos/clip_text
v_feat_dim: 2818
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast_uvcom/tacos
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# tacos-specific params
lw_saliency: 4
lr: 0.0002
lr_drop: 40
max_v_l: -1
max_q_l: 100
eval_bsz: 32

# uvcom-specific params
enc_layers: 3
dec_layers: 3
num_queries: 30
n_txt_mu: 5
n_visual_mu: 30
sim_loss_coef: 1
neg_loss_coef: 0.5
lr_gamma: 0.1
neg_choose_epoch: 80
lr_drop: 100
em_iter: 5
cross_fusion: False