model_name: qd_detr
dset_name: tacos
ctx_mode: video_tef
v_feat_types: slowfast_clip
t_feat_type: clip
train_path: data/tacos/tacos_train_release.jsonl
eval_path: data/tacos/tacos_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tacos/clip', 'features/tacos/slowfast']
t_feat_dir: features/tacos/clip_text
v_feat_dim: 2818
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast_qd_detr/tacos
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# tacos-specific params
lw_saliency: 4
lr: 0.0002
lr_drop: 40
max_v_l: -1
max_q_l: 100
eval_bsz: 32