model_name: cg_detr
dset_name: tacos
ctx_mode: video_tef
v_feat_types: clip
t_feat_type: clip
train_path: data/tacos/tacos_train_release.jsonl
eval_path: data/tacos/tacos_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tacos/clip']
t_feat_dir: features/tacos/clip_text
v_feat_dim: 514
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_cg_detr/tacos
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

lw_saliency: 4
lr: 0.0002
lr_drop: 200

# CG-DETR-specific parameters
enc_layers: 3
dec_layers: 3
t2v_layers: 2
sent_layers: 1
moment_layers: 1
dummy_layers: 2
num_dummies: 50
total_prompts: 10
num_prompts: 2

lw_wattn: 1
lw_ms_align: 1
lw_distill: 1

max_v_l: -1
max_q_l: 100
eval_bsz: 32