model_name: eatr
dset_name: tacos
ctx_mode: video_tef
v_feat_types: resnet
t_feat_type: glove
train_path: data/tacos/tacos_train_release.jsonl
eval_path: data/tacos/tacos_test_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tacos/resnet']
t_feat_dir: features/tacos/glove
v_feat_dim: 2050
t_feat_dim: 300
aux_loss: True
results_dir: results/resnet_glove_eatr/tacos
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# charades-specific params
lw_saliency: 4
lr: 0.0002
lr_drop: 40
max_v_l: -1
max_q_l: 100
eval_bsz: 32

# EaTR-specific params
event_coef: 3