seed: 2018 # CGDETR TVSum
model_name: uvcom
dset_name: tvsum
ctx_mode: video_tef
v_feat_types: slowfast_clip
t_feat_type: clip
train_path: data/tvsum/tvsum_train_release.jsonl
eval_path: data/tvsum/tvsum_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tvsum/clip', 'features/tvsum/slowfast']
t_feat_dir: features/tvsum/clip_text
v_feat_dim: 2818
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_slowfast_uvcom/tvsum
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2
bsz: 4
max_q_l: 100
max_v_l: 1000

lr: 0.001
lr_drop: 2000
n_epoch: 2000

# uvcom-specific params
enc_layers: 3
dec_layers: 3
num_queries: 30
n_txt_mu: 5
n_visual_mu: 30
sim_loss_coef: 1
neg_loss_coef: 0.5
lr_gamma: 0.1
neg_choose_epoch: 80
em_iter: 5
cross_fusion: False