seed: 2018 # CGDETR TVSum
model_name: tr_detr
dset_name: tvsum
ctx_mode: video_tef
v_feat_types: i3d
t_feat_type: clip
train_path: data/tvsum/tvsum_train_release.jsonl
eval_path: data/tvsum/tvsum_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/tvsum/i3d']
t_feat_dir: features/tvsum/clip_text
v_feat_dim: 2050
t_feat_dim: 512
aux_loss: True
results_dir: results/i3d_clip_tr_detr/tvsum
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2
bsz: 4
max_q_l: 100
max_v_l: 1000

lr: 0.001
lr_drop: 2000
n_epoch: 1000
eval_epoch_interval: 5

# TR-DETR specific losses
VTC_loss_coef: 0.5
CTC_loss_coef: 2