model_name: moment_detr
dset_name: activitynet
ctx_mode: video_tef
v_feat_types: clip
t_feat_type: clip
train_path: data/activitynet/activitynet_train_release.jsonl
eval_path: data/activitynet/activitynet_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/ActivityNet/clip']
t_feat_dir: features/ActivityNet/clip_text
v_feat_dim: 514
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_moment_detr/activitynet
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2