model_name: taskweave
dset_name: activitynet
ctx_mode: video_tef
v_feat_types: resnet
t_feat_type: glove
train_path: data/activitynet/activitynet_train_release.jsonl
eval_path: data/activitynet/activitynet_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/ActivityNet/resnet']
t_feat_dir: features/ActivityNet/glove
v_feat_dim: 2050
t_feat_dim: 300
aux_loss: True
results_dir: results/resnet_glove_taskweave_mr2hd/activitynet
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 2

# Taskweave-specific; This model needs to train MR2HD and HD2MR for MR and HD, respectively.
# If mr2hd is False, the strategy is HD2MR
mr2hd: True
model_ema: True