seed: 2018
model_name: eatr
dset_name: youtube_highlight
ctx_mode: video_tef
v_feat_types: clip
t_feat_type: clip
train_path: data/youtube_highlight/youtube_highlight_train_release.jsonl
eval_path: data/youtube_highlight/youtube_highlight_val_release.jsonl
eval_split_name: val
v_feat_dirs: ['features/youtube_highlight/clip']
t_feat_dir: features/youtube_highlight/clip_text
v_feat_dim: 514
t_feat_dim: 512
aux_loss: True
results_dir: results/clip_eatr/youtube_highlight
ckpt_filename: best.ckpt
train_log_filename: train.log
eval_log_filename: val.log
clip_length: 1
bsz: 4
max_v_l: 1000

lw_saliency: 4
lr: 0.0002
lr_drop: 2000
n_epoch: 1000

# EaTR-specific params
event_coef: 3