name: Run mypy

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Run mypy install
        run: pip install mypy

      - name: Run mypy
        run: find lighthouse -type f -name "*.py" -not -path 'lighthouse/common/*' | xargs mypy
